# SPDX-FileCopyrightText: 2023 David Runge <dave@sleepmap.de>
# SPDX-FileCopyrightText: 2023 Wiktor Kwapisiewicz <wiktor@metacode.biz>
# SPDX-License-Identifier: CC0-1.0

[advisories]
unmaintained = "deny"
yanked = "deny"
ignore = [
]

[bans]
deny = [
]

[licenses]
allow = [
  "Apache-2.0",
  "MIT",
]
