# SPDX-FileCopyrightText: 2023 Wiktor Kwapisiewicz <wiktor@metacode.biz>
# SPDX-License-Identifier: CC0-1.0

name: CI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
  pull_request:

jobs:
  check-files:
    name: Check files in the latest commit
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - run: pacman -Sy --needed --noconfirm archlinux-keyring
      - run: pacman -Syu --needed --noconfirm just
      - uses: actions/checkout@v4
      - run: just install
      - run: CARGO_TARGET_DIR=/tmp/cargo just ci
      - if: "startsWith(github.ref, 'refs/tags/')"
        run: cargo set-version $(printf "{{ github.refname }}" | sed s/^v//) && cargo publish --allow-dirty --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
