# SPDX-FileCopyrightText: 2023 Wiktor Kwapisiewicz <wiktor@metacode.biz>
# SPDX-License-Identifier: CC0-1.0

name: CI

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
  pull_request:

jobs:
  check-files:
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - run: pacman -Sy --needed --noconfirm archlinux-keyring
      - run: pacman -Syu --needed --noconfirm just
      - uses: actions/checkout@v2
      - run: just install
      - run: CARGO_TARGET_DIR=/tmp/cargo just ci

  publish:
    name: Publish on crates.io
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    needs: [check-files]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
