# SPDX-FileCopyrightText: 2023 Wiktor Kwapisiewicz <wiktor@metacode.biz>
# SPDX-License-Identifier: CC0-1.0

name: CI

on: pull_request

jobs:
  check-files:
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - run: pacman -Sy --needed --noconfirm archlinux-keyring
      - run: pacman -Syu --needed --noconfirm just
      - uses: actions/checkout@v2
      - run: just install
      - run: CARGO_TARGET_DIR=/tmp/cargo just ci
